### ISSUE TITLE
It works for the STL, but not for C++ at all

### ISSUE THREAD

**Issue by yh-sb** [tushortz/CPP-Completions#1]
This plugin does not provide completion in a wide sense of this word. This plugin only works for completion of the STL. This should be written in the description to avoid confusion.

**Comment by tushortz** [comment]
Thanks for your information. I was planning on improving it more as time goes by but I think a rename might be a good option as well. What do you mean by works for STL but not for C++.  @r44083

**Comment by yh-sb** [comment]
Good idea. I mean "works with STL only". (https://en.wikipedia.org/wiki/Standard_Template_Library) Isn't it?

**Comment by tushortz** [comment]
I guess by saying STL you mean Sublime Text. Yeah it is meant to work for Sublime Text only according to the description. Except if I don't understand you well. @r44083

**Comment by yh-sb** [comment]
I mean that this plugin doesn't provide IntelliSense https://en.wikipedia.org/wiki/Intelligent_code_completion

**Comment by tushortz** [comment]
It shouldnt provide intellisense because Sublime Text is not an IDE. It's
just a customizable text editor. Perhaps, It may be possible to do that but
I have no idea about it.

**Comment by tushortz** [comment]
https://www.dropbox.com/sh/5kabm9zdhk8i1xw/AAChgHPv0E77pzOmaho-tC3ja?dl=0
